backend:
  name: github
  repo: magallen100-ux/tienda-hogar # Cambia por tu usuario/repo real de GitHub (ej: tu-nombre/cortinajes-ivanna)
  branch: main
  base_url: https://cortinajesivanna.com # O tu dominio principal
  auth_endpoint: /api/auth

media_folder: "img"
public_folder: "img"

collections:
  - name: "galeria"
    label: "Galería de Trabajos"
    files:
      - file: "content/galeria.json"
        label: "Fotos de la Galería"
        name: "galeria_data"
        fields:
          - label: "Categorías de la Galería"
            name: "items"
            widget: "list"
            fields:
              - { label: "Título de la Categoría", name: "titulo", widget: "string" }
              - { label: "Descripción Corta", name: "descripcion", widget: "string" }
              - label: "Imágenes de esta categoría"
                name: "imagenes"
                widget: "list"
                field: { label: "Imagen", name: "foto", widget: "image" }