backend:
  name: github
  repo: magallen100-ux/tienda-hogar
  branch: main
  base_url: https://cortinajesivanna.com
  auth_endpoint: /api/auth

media_folder: "img"
public_folder: "img"

collections:
  - name: "categorias_galeria"
    label: "Categorías de la Galería"
    label_singular: "Categoría"
    folder: "content/galeria"
    create: true
    slug: "{{fields.slug}}"
    format: "json"
    fields:
      - { label: "Identificador Web (Slug)", name: "slug", widget: "string", hint: "Escribe el nombre en minúsculas y con guiones (ej: verticales-noche-dia)" }
      - { label: "Nombre de la Categoría", name: "titulo", widget: "string", hint: "Ej: Verticales Noche/Día" }
      - { label: "Descripción Corta", name: "descripcion", widget: "text", required: false }
      - { label: "Orden de aparición", name: "orden", widget: "number", default: 1, value_type: "int" }
      - label: "Fotos de esta categoría"
        name: "imagenes"
        widget: "list"
        summary: '{{fields.foto}}'
        fields:
          - { label: "Imagen", name: "foto", widget: "image" }
          - { label: "Título / Pie de foto", name: "titulo_foto", widget: "string", required: false }